Login
omerjacobi/flatfinder pull request #3
Opened 2018-12-06 11:40 UTC by yael-renous

login to facebook and retrieves posts from group

2018-12-09 15:14 UTC, omerjacobi requested changes
we need to fill the code of LoginResult
onCancel
onError

2018-12-10 13:03 UTC, m-mandel requested changes
Hi ~ good job~ 🥇  fix and send it again...

2018-12-10 13:03 UTC, mosem commented on app/src/main/java/com/huji/cse/flatfinder/MainActivity.java
> +                    public void onCancel() {
is it really necessary?

2018-12-10 13:03 UTC, mosem commented on app/src/main/java/com/huji/cse/flatfinder/MainActivity.java
> +    private void get_posts_in_graph(LoginResult loginResult) {
Conventions!!! Use camel case..

2018-12-10 13:03 UTC, mosem commented on app/src/main/java/com/huji/cse/flatfinder/MainActivity.java
> +        request.setGraphPath("337906013661346/feed?fields=link,message,created_time,name,full_picture,id");
why not constant?

2018-12-10 13:03 UTC, mosem commented on .idea/gradle.xml
>    <component name="GradleSettings">
👍

2018-12-10 13:03 UTC, mosem commented on app/src/main/java/com/huji/cse/flatfinder/MainActivity.java
> +                    public void onCancel() {
yes.. it won;t work

2018-12-10 14:42 UTC, omerjacobi reviewed
greate job

2018-12-10 14:44 UTC, omerjacobi commented
finish code review on facebook login

2018-12-10 14:44 UTC, merged